### ISSUE TITLE
there are some inconsistencies across packages for cohort counts: double vs integer64

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/OMOPGenerics#40] opened 2023-11-10 10:23 UTC
I will require in generateCohortSet a specific type.

Any thoughts @edward-burn @ablack3 ?

**Comment by edward-burn** [comment] 2023-11-15 12:29
Can we simply coerce to as.integer when doing the export?

**Comment by edward-burn** [comment] 2023-12-06 19:23
#60

**Comment by ablack3** [comment] 2023-12-11 11:08
This is a problem in R which does not have a native 64 bit integer type. It only has 32 bit integers. However there is the bit64 package that adds a 64 bit integer type.  doubles can store larger values than 32 bit integers but suffer from floating point precision issues.

But we need to be a little more precise here. Because it's not clear to me what exactly we are talking about  in this issue 😆 

> I will require in generateCohortSet a specific type.

A type for what exactly?

> Can we simply coerce to as.integer when doing the export?

Export what from where to where?

**Comment by edward-burn** [comment] 2023-12-11 11:10
I believe this was just talking about the cohort count attributes and the tibble potentially having different types (which can cause problems when joining results from multiple data partners), but this should have been fixed by https://github.com/darwin-eu-dev/OMOPGenerics/pull/60

**Comment by ablack3** [comment] 2023-12-11 11:12
I think the issue is about mapping data types from the database cdm specification to R. The main one that causes problems is int64 -> integer (32 bit) because you could lose precision.

**Closed** 2023-12-13 15:45 UTC
Labels: requires discussion
